export const metadata = {
    title: 'Next.js',
    description: 'Generated by Next.js',
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <>
            {children}
            <h1>product review page</h1>
        </>
    )
}
// this page show the immediate page.tsx page that is product/[productId]/page.tsx and product/[productId]/reviews/[reviewsId]/page.tsx and product/[productId]/reviews/page.tsx