import { Metadata } from "next"
export const metadata: Metadata = {
  title: {
    default: "this is default title", //the page have no metadata use this title as default
    // absolute: "absolute", //overwrite the title
    template: "%s | pritam",//add something in title
  },
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <header style={{
          backgroundColor: "lightblue"
        }}>
          <h1>this is header</h1>
        </header>
        {children}
        <footer style={{
          backgroundColor: "lightblue"
        }}>
          <h1>this is footer</h1>
        </footer></body>
    </html>
  )
}
