export const metadata = {
    title: 'Next.js',
    description: 'Generated by Next.js',
}

export default function MarketLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
            <body>
                <header style={{
                    backgroundColor: "lightblue"
                }}>
                    <h1>this is header</h1>
                </header>
                {children}
                <footer style={{
                    backgroundColor: "lightblue"
                }}>
                    <h1>this is footer</h1>
                </footer></body>
        </html>
    )
}
